export const FETCH_ALL_USER_LIST = "FETCH_ALL_USER_LIST";
export const FETCH_ALL_USER_LIST_SUCCESS = "FETCH_ALL_USER_LIST_SUCCESS";
export const FETCH_ALL_USER_LIST_FAILURE = "FETCH_ALL_USER_LIST_FAILURE";
